### ISSUE TITLE
Edit User's Name not updating data

### ISSUE THREAD

**Issue by pabloredsky** [redsky-engineering/ssh-key-manager#1]
The modal "Edit User's Name" is not updating the data in json file. Also, there isn't any notice (toast) telling that there was an error

![Screenshot 2024-09-19 at 10 48 13](https://github.com/user-attachments/assets/2f5bc139-d819-49d2-a1ec-ed3e50611ebf)

**Comment by JoshuaHintze** [comment]
fixed by #3
